Sql training
thisisrocee/SQL_training_rocee pull request #1
Opened 2023-04-16 13:37 UTC by thisisrocee

2023-04-21 14:37 UTC, EdgarsSalmins commented on sql-movies/test/08-integrity.test.ts
> +      AND id NOT IN (SELECT DISTINCT genre_id FROM movie_genres)`;
te bija jābūt parastiem delete vaicājumiem un tas ka neizdzēšas bija jāpanāk ar Foreign key un on delete/update restrict/cascade. :)

2023-04-21 14:37 UTC, EdgarsSalmins commented on sql-movies/test/08-integrity.test.ts
> +      AND id NOT IN (SELECT DISTINCT genre_id FROM movie_genres)`;
attiecas uz visiem integrity tests

2023-04-21 14:38 UTC, EdgarsSalmins requested changes
integrity tests nav pareizi. :) tas kā uztaisīts ir workaround lai netaisītu foreign keys. :)

2023-04-21 14:45 UTC, thisisrocee commented
> integrity tests nav pareizi. :) tas kā uztaisīts ir workaround lai netaisītu foreign keys. :)

i mean as long as it works right😂, but no i gacho! izlabošu!

2023-04-24 05:15 UTC, EdgarsSalmins approved these changes

2023-04-24 05:15 UTC, merged